channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - pip=21.2.4
  - pip:
      - azureml-mlflow==1.51.0
      - azure-ai-ml==1.0.0
      - pyarrow==10.0.0
      - scikit-learn==0.24.1
      - scipy==1.7.1
      - pandas==1.2.1
      - joblib==1.0.0
      - matplotlib==3.3.3
      - git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-client
      - git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-collector